server:
  port: 0


spring:
  application:
    name: atm-service
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:4001/eureka"


bank:
  url:
    auth: "http://BANK-SERVICE/bank/service/authenticate"
    init: "http://BANK-SERVICE/bank/service/initialize"
    balance: "http://BANK-SERVICE/bank/service/balance"
    deposit: "http://BANK-SERVICE/bank/service/deposit"
    withdrawal: "http://BANK-SERVICE/bank/service/withdrawal"


management:
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      authenticateUserCard:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED