server:
  port: 0

spring:
  application:
    name: bank-service

  devtools:
    restart:
      enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/bankdb"
    username: postgres
    password: root123
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    show-sql: true
    properties:
      hibernate:
        proc:
          param_null_passing: true
    generate-ddl: on

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka

jwt:
  token:
    secret: super_secret
    expiration:
      time: 6000000

authenticate:
  url:
    path: "/bank/service/authenticate"

bank:
  deposit:
    threshold: 100000
  withdrawal:
    threshold: 10000